<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>8051c984-585b-4a5e-b6d7-833e5dd4afe7</UserSecretsId>
		<Version>2.0.0</Version>
		<InformationalVersion>2.0.0</InformationalVersion>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Identity" Version="1.17.1" />
		<PackageReference Include="GovUK.Dfe.CoreLibs.Security" Version="1.1.28-prerelease.26" />
		<PackageReference Include="GovUk.Frontend.AspNetCore" Version="3.2.2" />
		<PackageReference Include="HtmlSanitizer" Version="9.0.892" />
		<PackageReference Include="Markdig" Version="0.42.0" />
		<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.22.0" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\GovUK.Dfe.FlexForms.Application\GovUK.Dfe.FlexForms.Application.csproj" />
		<ProjectReference Include="..\GovUK.Dfe.FlexForms.Infrastructure\GovUK.Dfe.FlexForms.Infrastructure.csproj" />
	</ItemGroup>

</Project>
