<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GovUK.Dfe.CoreLibs.Caching" Version="1.0.13" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.10" />
    <PackageReference Include="GovUK.Dfe.CoreLibs.Messaging.Contracts" Version="0.1.5" />
    <PackageReference Include="GovUK.Dfe.CoreLibs.Messaging.MassTransit" Version="0.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.3.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GovUK.Dfe.FlexForms.Application\GovUK.Dfe.FlexForms.Application.csproj" />
  </ItemGroup>

</Project>
